### ISSUE TITLE
Plotting 

### ISSUE THREAD

**Issue by zabana31** [orlox/mkipp#2]
Greetings all:

I am using the codes written to make my plots but i did not know how to add the mixing regions and mlx_relr_regions, i have tried this, is it ok or not ? If not how i add them correctly ? 

Also there is codes for abundances and HR diagrams ? 

Thanks all

       mx1_top
      mx1_bot
      mx2_top
      mx2_bot
     mixing_regions 20
     burning_regions 20
     mix_relr_regions

**Comment by orlox** [comment]
Hi,

for the mix_relr_regions, you also need to specify an integer (i.e., "mix_relr_regions 20")

**Comment by orlox** [comment]
And regarding abundances and HR diagrams, this is only meant to automate Kippenhahn diagrams. You can read history files into MESA using the mesa_data.py class that is included, doing

import mesa_data
history = mesa_data.Mesa_Data("LOGS/history.data")

then you can access any information on history.data by doing history.get("column_name"). You can do exactly the same with profile files, from which you can get the abundances. To plot those arrays, you need to use standard matplotlib routines, check those here:

https://matplotlib.org/users/pyplot_tutorial.html
