### ISSUE TITLE
Kippenhahn6.png it's all blurred

### ISSUE THREAD

**Issue by Guglielmo95** [orlox/mkipp#5]
Hi, 
I'm trying to use mkipp.py in order to plot some kippenhahn diagrams from my models. I used a multi-inlist structure for them so for each inlist file I have a LOGS directory with history.data and profile files. If I submit my data to the python program, for example the one that makes kippenhahn.png, then everything is fine. But if I try to do the same thing with the last one in the example.py, which yields kippenhahn6.png, then my plot is all blurred (like bigger pixels forming the plot)
![Kippenhahn6](https://user-images.githubusercontent.com/64073855/79854449-bc5b8100-83c9-11ea-98d5-d044d282474b.png)
![Kippenhahn10](https://user-images.githubusercontent.com/64073855/79854473-c54c5280-83c9-11ea-9d5a-a4d8b5388f62.png)

. The only thing that I do is just use my data instead of those provided in the directory LOGS. I don't understand why this happens. I tried to set the integer after mixing_regions and mix_relr_regions equal to that one in the provided data (20) but doesn't seems to matter. If you could help with this issues I'd be very grateful, thank you very much for your time. 
Best regards, 
Guglielmo

**Comment by Guglielmo95** [comment]
![Kippenhahn](https://user-images.githubusercontent.com/64073855/79855541-6556ab80-83cb-11ea-9dcf-00bdfed049d4.png)
![Kippenhahn9](https://user-images.githubusercontent.com/64073855/79855550-68519c00-83cb-11ea-9e6f-af7e07bfdac2.png)

**Comment by orlox** [comment]
Hi Guglielmo, I wanted to take a look at this but hadn't found the time yet. Since you closed the issue, did you managed to find a solution?

**Comment by Guglielmo95** [comment]
Hi, yes: I set the history_interval to 1 and so the plot isn't full of "pixels" anymore(guess better resolution) and I added some other mix tipes to the  kippenhahn 6 plot. Then I tried to plot a kippenhahn diagram like your 6th example but with the xaxis from the 4th one (but in my case reversed, so t-tf). Here I bumped into another problem: compared to my example 6th-like diagram this new one has a problem towards the right edge since didnt show the hole data available 'cause of the log scale. I fixed this, I dont even know how, by changing the constant in the xaxis formula: now I have 0,000000001. Could you explaine how this is possibile? Why I had to change this constant in order to have a full diagram with my data?
Thanks for your time, best regards

Guglielmo

Scarica Outlook per iOS<https://aka.ms/o0ukef>
________________________________
Da: Pablo Marchant <notifications@github.com>
Inviato: Friday, April 24, 2020 4:32:46 PM
A: orlox/mkipp <mkipp@noreply.github.com>
Cc: Guglielmo95 <guglielmogosh@hotmail.it>; State change <state_change@noreply.github.com>
Oggetto: Re: [orlox/mkipp] Kippenhahn6.png it's all blurred (#5)


Hi Guglielmo, I wanted to take a look at this but hadn't found the time yet. Since you closed the issue, did you managed to find a solution?

**Comment by orlox** [comment]
Closing this as the last comment refers to a different problem. @Guglielmo95 , it's been a while since you made the comment but if there's still an issue that you think needs attention please create a different issue.
