### ISSUE TITLE
eps_nuc

### ISSUE THREAD

**Issue by AmedeoRom** [orlox/mkipp#6]
Hi!!

Sorry, probably a stupid question.

In your readme you say "values such as eps_nuc need to be added to profile_columns.list as well", but apparently nothing in the list corresponds to a "eps_nuc" value. There are plenty that indeed have it in their name, but none of them when added change the error

"Couldn't read profile .../LOGS/profile1.data 'eps_nuc'"

**Comment by orlox** [comment]
You need to configure your MESA simulation to include that column in your profile files. You can follow how to add columns to your profiles here:
http://mesa.sourceforge.net/output.html
copy the full profile_columns.list file in $MESA_DIR/star/defaults and uncomment eps_nuc
